/* A real, valid PDF built here in about forty lines, rather than a binary
   blob committed into the repo.

   It exists for one reason: audit/measure.mjs walks every screen this app
   has, and two of them -- the PDF reader's own two sheets, including the
   .sheet-lead paragraph -- can only be reached with a PDF actually open.
   No PDF is seeded onto the shelf (the shelf ships two INCLUDED books and
   that is a product decision, not an audit one), so the audit imports this
   one through the app's own file picker at run time and deletes it after.

   Deliberately plain: two pages, Helvetica, enough prose that the page is
   not blank on screen. It is scaffolding for a measurement, not a specimen
   of typesetting. */

const PAGES = [
    [
        'Flyleaf eReader - audit fixture',
        '',
        'This file is generated by audit/fixture-pdf.mjs and imported by',
        'audit/measure.mjs so that the PDF reader, and the two sheets that',
        'only exist while a PDF is open, can be measured like every other',
        'screen in the app.',
        '',
        'It is not shipped, it is not seeded onto the shelf, and it is',
        'removed from disk once the audit run finishes.',
    ],
    [
        'Page two',
        '',
        'A second page, so that the reader has something to scroll and the',
        'page count in the chrome reads plausibly rather than reading one.',
    ],
]

function stream(lines) {
    const body = lines
        .map((l, i) => `BT /F1 ${i === 0 ? 18 : 11} Tf 72 ${720 - i * 22} Td (${l.replace(/([()\\])/g, '\\$1')}) Tj ET`)
        .join('\n')
    return body
}

export function fixturePdf() {
    const objs = []
    const contents = PAGES.map(stream)

    objs[1] = '<< /Type /Catalog /Pages 2 0 R >>'
    objs[2] = `<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>`
    objs[3] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R >>'
    objs[4] = `<< /Length ${contents[0].length} >>\nstream\n${contents[0]}\nendstream`
    objs[5] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>'
    objs[6] = `<< /Length ${contents[1].length} >>\nstream\n${contents[1]}\nendstream`
    objs[7] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'

    let out = '%PDF-1.4\n'
    const offsets = []
    for (let i = 1; i < objs.length; i++) {
        offsets[i] = out.length
        out += `${i} 0 obj\n${objs[i]}\nendobj\n`
    }
    const xref = out.length
    out += `xref\n0 ${objs.length}\n0000000000 65535 f \n`
    for (let i = 1; i < objs.length; i++) out += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`
    out += `trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`
    return Buffer.from(out, 'latin1')
}
