/* A printer's lozenge with a lozenge counter. NOT Press's five-petal rosette:
   the owner asked for a mark that does not read as the same app, and these are
   three distinct products, so the eReader gets its own. Same world — a plain
   geometric printer's ornament, ink on paper, no colour of its own — and a
   deliberately quieter form beside the rosette's ornate one. It inherits
   colour: chrome is ink on paper, never terracotta.

   Chosen over sixteen other candidates across five rounds (the comparison
   sheets are in /tmp/fl/mark/, generated by gen*.mjs). The ones that failed
   failed on MEANING, not craft, and each failure is a trap worth not
   re-entering: any rearrangement of Press's near-circular petal reads as
   blobs; a four- or eight-pointed radial form reads as the AI-sparkle glyph,
   which is actively wrong for an app whose brief bans AI; leaves from a common
   base read as a lotus or a spa; a leaf over a dot reads as an exclamation
   mark; a bar with a lozenge on it collapses to a `+` at 18px; two offset
   lozenges collapse to a lightning bolt. A five-pointed star would have read
   as a rating and a six-pointed one as a snowflake.

   The counter is an exact 0.443 scale of the outer, and it is drawn as a
   SECOND SUBPATH WITH REVERSED WINDING (256,164 → 194,256 → 256,348 →
   318,256 runs anticlockwise where the outer runs clockwise), so the default
   nonzero fill rule makes it a hole. That keeps the whole mark one `d` string
   with a plain `fill`, which is what lets the same constant serve this
   component, scripts/make-icons.mjs and index.html's inline splash — none of
   which sets `fill-rule`. Reverse either subpath and the counter fills in.

   Symmetric about x=256 and y=256, bounding box 116–396 × 48–464. Both facts
   are load-bearing: make-icons.mjs centres the 512 box rather than the ink,
   and derives its scale from the ink's 0.8125 fraction of that box. */

export const MARK = 'M256 48 L396 256 L256 464 L116 256 Z M256 164 L194 256 L256 348 L318 256 Z'

export function Mark({ size = 24 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 512 512" aria-hidden="true" style={{ display: 'block' }}>
      <path d={MARK} fill="currentColor" />
    </svg>
  )
}
